#!/usr/bin/env bash
# This script displays numbers 1-20 and adds superstitious messages for certain numbers

count=1
while [ $count -le 20 ]; do
    echo $count
    case $count in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((count++))
done
